### ISSUE TITLE
The column name 'dec' in table 'targetsX' is a reserved word of monetDB

### ISSUE THREAD

**Issue by excelwang** [wan-meng/gwac_pipeline#1]
The column name 'dec' in table 'targetsX' is a reserved word of monetDB. So it will cause the bellow error when 'dec' appears in the where clause or the select clause.
<img width="769" alt="2016-11-10 1 18 44" src="https://cloud.githubusercontent.com/assets/7976028/20165446/476a2ccc-a748-11e6-8c14-18c51f611780.png">
 Is there any other reason for the above error?
A workable solution will be very appreciated!

**Comment by wan-meng** [comment]
Sorry for seeing your issue just now, you can just add a double quotation mark on dec, like "dec".

**Comment by wan-meng** [comment]
How did you find my code? Could you tell me who you are, thanks a lot!

**Comment by excelwang** [comment]
Thanks a lot! I am Wang Huajin of CNIC.
